In [1]:
from utils.build_features import build_features
from utils.utils import get_klines, y_to_bins
from binance.client import Client
import pandas as pd
import numpy as np

from models.random_forest import RandomForest

C:\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
# Hyper parameters:
CUTOFF = 0.15  # in percents. The minimal value of ascending
N_ESTIMATORS = 100


In [3]:
s_date = '01 Jan, 2019'
e_date = '03 Jan, 2019'
symbol = 'BTCUSDT'
interval = Client.KLINE_INTERVAL_30MINUTE


In [5]:

kl_f_name = symbol + '_' + s_date + '_TO_' + e_date + '.csv'
# klines = get_klines(s_date, e_date, symbol, interval)
# klines.to_csv('klines/30M/' + kl_f_name, index=False)
klines = pd.read_csv('klines/30M/' + kl_f_name)

In [6]:
print(klines.shape)
klines.head()

(49, 7)


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>timestamp</th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>Number of trades</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.546301e+12</td>
      <td>3701.23</td>
      <td>3713.00</td>
      <td>3689.88</td>
      <td>3700.31</td>
      <td>686.367420</td>
      <td>5534.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1.546304e+12</td>
      <td>3700.20</td>
      <td>3702.73</td>
      <td>3684.22</td>
      <td>3689.69</td>
      <td>613.539115</td>
      <td>5086.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1.546308e+12</td>
      <td>3689.67</td>
      <td>3695.95</td>
      <td>3675.04</td>
      <td>3690.00</td>
      <td>895.302181</td>
      <td>6391.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1.546312e+12</td>
      <td>3690.00</td>
      <td>3699.77</td>
      <td>3685.78</td>
      <td>3693.13</td>
      <td>796.714818</td>
      <td>5709.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>1.546315e+12</td>
      <td>3692.32</td>
      <td>3720.00</td>
      <td>3685.94</td>
      <td>3692.71</td>
      <td>1317.452909</td>
      <td>7908.0</td>
    </tr>
  </tbody>
</table>
</div>

In [16]:


features_f_name = symbol + '_' + s_date + '_TO_' + e_date + '.csv'
# features = build_features(klines)
# features.to_csv('features/30M/' + features_f_name, index=False)
features = pd.read_csv('features/30M/' + features_f_name)



In [17]:
features['TO_PREDICT'] = features['close_ratio'].shift(-1)
features = y_to_bins(features, 'TO_PREDICT', CUTOFF)

In [18]:
features[['close', 'y_bins']].head(10)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>close</th>
      <th>y_bins</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3693.54</td>
      <td>-1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>3686.32</td>
      <td>-1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3659.41</td>
      <td>5</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3696.73</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>3719.00</td>
      <td>-1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>3708.21</td>
      <td>-1</td>
    </tr>
    <tr>
      <th>6</th>
      <td>3711.20</td>
      <td>10</td>
    </tr>
    <tr>
      <th>7</th>
      <td>3797.14</td>
      <td>-1</td>
    </tr>
    <tr>
      <th>8</th>
      <td>3778.02</td>
      <td>-1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>3770.00</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

In [29]:
l = features.shape[0]
X_train = np.array(features.iloc[:int(0.8 * l)].drop(['timestamp', 'y_bins'], axis=1))
X_valid = np.array(features.iloc[int(0.8 * l):].drop(['timestamp', 'y_bins'], axis=1))
y_train = np.array(features['y_bins'].iloc[:int(0.8 * l)])
y_valid = np.array(features['y_bins'].iloc[int(0.8 * l):])
df_valid = features.iloc[int(0.8 * l):]


In [30]:
model = RandomForest(n_estimators=N_ESTIMATORS)

In [31]:
model.fit(
    X=X_train,
    y=y_train)

In [32]:
df_valid['predictions'] = model.predict(df_valid.drop(['timestamp', 'y_bins'], axis=1))
pred_file_name = 'try.csv'
df_valid.to_csv('predictions/'+pred_file_name, index=False)

[0.44 0.35 0.13 0.08]
[0.67 0.22 0.05 0.06]
[0.86 0.09 0.05 0.  ]
[0.84 0.1  0.04 0.02]
[0.8  0.13 0.05 0.02]
[0.74 0.2  0.03 0.03]
[0.14 0.79 0.05 0.02]


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
